[workspace]
members = [
  "daemon",
  "phantom",
]

[patch.crates-io]
daemon = { path = "daemon" }
phantom = { path = "phantom" }
ntex-files = { git = "https://github.com/ntex-rs/ntex-extras.git" }
