[workspace]
members = [
  "nanocld",
  "nanocli",
]

[patch.crates-io]
nanocld = { path = "nanocld" }
nanocli = { path = "nanocli" }
ntex-files = { git = "https://github.com/ntex-rs/ntex-extras.git" }
