[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.test]
command = "cargo"
args = ["llvm-cov", "nextest"]

[tasks.my-flow]
dependencies = [
    "build",
    "test"
]
