[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.23"
env_logger = "0.8"
ntex = { version = "0.5", features = ["openssl", "rustls", "tokio"] }
serde = { version = "1.0", features = ["derive"] }