[package]
name = "rsocknet"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
serde_json = "1.0.81"
ntex-files = "0.1"
serde = { version = "1.0", features = ["derive"] }
ntex = { version = "0.5", features = ["openssl", "rustls", "tokio"] }
