name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install ubuntu dependencies
      run: sudo sh ./scripts/ubuntu.deps.sh
    - name: Install docker
      run: sudo sh ./scripts/install_docker.ubuntu.sh
    - name: Install rust dependencies
      run: sh ./scripts/rust.deps.sh
    - name: Install nanocl
      run: sudo sh ./scripts/install_nanocl.ubuntu.sh
    - name: Start docker and containerd
      run: sudo sh ./pre_start.sh
    - name: Run tests
      run: cargo make test --verbose
