name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: llvm-tools-preview
    - uses: davidB/rust-cargo-make@v1
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: taiki-e/install-action@nextest
    - name: Install ubuntu dependencies
      run: sudo sh ./scripts/ubuntu.deps.sh
    - name: Install docker
      run: sudo sh ./scripts/install_docker.ubuntu.sh
    - name: Install nanocl
      run: sudo sh ./scripts/install_nanocl.sh
    - name: Start docker and containerd
      run: sudo sh ./scripts/pre_start_nanocl.sh
    - name: Ci file perm
      run: sudo chmod 777 /run/nanocl && sudo chmod 777 /var/lib/nanocl
    - name: Run tests
      run: cargo make test
