[package]
name = "dockerust"
version = "0.1.0"
edition = "2021"

[lib]
name = "dockerust"
path = "src/dockerust.rs"

[dependencies]
ntex = { version = "0.5", features = ["openssl", "rustls", "tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
